### PR TITLE
Use HTTP with streamed body

### PR DESCRIPTION
**Pull request by MatMaul**
This avoids caching the whole body in memory.

### CODE REVIEW

**Comment by renefloor** [comment]
Great idea, I'll try to change it a bit so it's not a breaking change.

**Comment by MatMaul** [comment]
Hi @renefloor, I have pushed an update which should not break the API.
It is untested yet, but quite straightforward.

**Comment by MatMaul** [comment]
@renefloor I can see some activity so I am shamelessly pushing up this PR 🙂

**Comment by renefloor** [comment]
Please don't close/reopen a PR to get my attention. I can only work on it when I have time.

It's true though that I have more time to work on this now and I will focus on the WebHelper next.

**Comment by MatMaul** [comment]
Sorry this part was a fat finger mistake, I just wanted to tag you as a heads up. Not complaining, just bumping because I saw some activity.

**Comment by renefloor** [comment]
Sorry, tried to merge develop into this branch, because it has some merge conflicts, but made an error

**Comment by MatMaul** [comment]
I am lost :) do you want me to rebase on develop ?

**Comment by MatMaul** [comment]
Ok nevermind I updated but it's useless, just saw your other PR ! Closing then thanks.

**Pull request closed without merging**
