### PR TITLE
Added get cache size

### PR DESCRIPTION
**Pull request by lijy91**

### CODE REVIEW

**Comment by renefloor** [comment]
@lijy91 I changed some code in the pull request. What do you think?

**Comment by lijy91** [comment]
@renefloor I have a question, why not use the sync method?

**Comment by renefloor** [comment]
Because writing and reading to/from disk is slow. Checking whether a directory exists is reading from disk and thus it is slow. When you do this synchronous you will block your main thread. When doing this async other dart code can continue to execute. 

Some docs about sync/async and threading in dart:
https://medium.com/flutter-community/futures-async-await-threading-in-flutter-baeeab1c1fe3
https://buildflutter.com/flutter-threading-isolates-future-async-and-await/

**Comment by lijy91** [comment]
@renefloor Got it

**Comment by renefloor** [comment]
Btw, I just did a test on the code and it returns the size of the folder, but not the files in the folder. I guess you have to loop over all the files in there. 

I always got a size of 3488, whether I clicked on 'clear cache' or not. Turns out the folder itself is 3,4KB.

cache size

**Pull request closed without merging**
